#!/bin/bash

set -eu

dir="${HOME}/github/sdk"
export PATH="${dir}/out/ReleaseX64/dart-sdk/bin:${PATH}"
export DDC_PATH="${dir}/pkg/dev_compiler"
export NODE_PATH="${DDC_PATH}/lib/js/common:."
dart $DDC_PATH/bin/dartdevc.dart --modules node "$@"
