#!/bin/sh

# link TARGET NAME
#
# Creates a symbolic link from NAME to TARGET, printing the result.
#
# If NAME already exists and is not a link to TARGET, it is first moved to
# "NAME.original".
link () {
  [[ "$1" && "$2" ]] || return
  local -r target="$1"
  local name="$2"
  if [[ ! -L "${name}" && -d "${name}" ]]; then
    name+="$(basename ${target})"
  fi
  readonly name

  echo -n "${name} -> ${target}"
  if [[ ! -e "${target}" ]]; then
    echo " (target doesn't exist)"
  elif [[ "$(readlink ${name})" == "${target}" ]]; then
    echo " (already exists)"
  else
    if [[ -e "${name}" || -L "${name}" ]]; then
      echo " (existing ${name} moved to ${name}.original)"
      mv "${name}"{,.original}
    else
      echo ""
    fi
    ln -s "${target}" "${name}"
  fi
}

# source_rc TARGET RC
#
# Sources TARGET from RC.
source_rc() {
  local -r target="$1"
  local -r rc="$2"
  local -r src="source ${target}"
  echo -n "${rc} => ${target}"
  if grep -Fxq "${src}" "${rc}" 2>/dev/null; then
    echo " (already exists)"
  else
    echo ""
    echo "${src}" >> "${rc}"
  fi
}

# prompt MSG
#
# Prints "Press [Enter] to MSG", then waits for [Enter] to be pressed.
prompt() {
  echo ""
  echo -e "\e[0;34mPress [Enter] to $1\e[m"
  read
}

install_tmux_plugins() {
  if [[ ! -e ".tmux/plugins/tpm/tpm" ]]; then
    git clone https://github.com/tmux-plugins/tpm .tmux/plugins/tpm
  fi
}

# install_vim_plugins
install_vim_plugins() {
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim +PlugClean +PlugInstall +GoInstallBinaries +qall
}

setup_dotfiles() {
  link "${dir}/bin/ddc" "bin/ddc"
  link "${dir}/dir_colors" ".dir_colors"
  link "${dir}/gitconfig" ".gitconfig"
  link "${dir}/gitignore" ".gitignore"
  link "${dir}/tmux.conf" ".tmux.conf"
  source_rc "${dir}/bashrc" ".bashrc"
  source_rc "${dir}/nvimrc" ".config/nvim/init.vim"
}

main() {
  set -eu

  local -r dir="$(realpath -s "$(dirname -- "$0")")"
  source "${dir}/install.sh"

  cd ~

  prompt "link (->) and source (=>) dotfiles"
  setup_dotfiles

  prompt "install tmux plugins"
  install_tmux_plugins

  prompt "install vim plugins"
  install_vim_plugins

  echo "Reopen any bash sessions to make use of the new goodness."
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
